name: Issue + PR management

on: [pull_request]

jobs:
  danger:
      runs-on: ubuntu-latest
      steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: '15.x'
            - run: yarn install
            - run: yarn run build
            - name: Danger JS Action
              uses: danger/danger-js@9.1.8
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
